global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'streamsocial-producer'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s
